<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Session;

class PropertyDetail extends Model
{
    use HasFactory;
    protected $table = 'property_details';
    protected $fillable = [
        'property_id',
        'bed',
        'bath',
        'garage',
        'floor',
        'room_size',
        'content',
        'video',
        'blocks',
        'parcel',
        'landscape',
        'season',
        'week',
        'view',
        'presentation',
        'cash',
        'installments',
        'available_floors',
        'balcony',
        'citizenship',
        'heating',
        'emptiness',
        'maintenance_fee',
        'creditability',
        'building_age',
        'units_infloors',
        'convertability',
        'total_units',
        'title_deed_type',
        'delivery_month',
        'deliver_year',
        'payment_options',
        'installment_months',
        'inside_project',
        'island_no',
        'sheet_no',
        'precedent_value',
        'gauge',
        'first_floor_title',
        'first_floor_size',
        'first_floor_max_size',
        'first_floor_rooms',
        'first_floor_baths',
        'first_floor_price',
        'first_floor_max_price',
        'first_floor_picture',
        'first_floor_description',
        'second_floor_title',
        'second_floor_size',
        'second_floor_max_size',
        'second_floor_rooms',
        'second_floor_baths',
        'second_floor_price',
        'second_floor_max_price',
        'second_floor_picture',
        'second_floor_description',
        'third_floor_title',
        'third_floor_size',
        'third_floor_max_size',
        'third_floor_rooms',
        'third_floor_baths',
        'third_floor_price',
        'third_floor_max_price',
        'third_floor_picture',
        'third_floor_description',
        'fourth_floor_title',
        'fourth_floor_size',
        'fourth_floor_max_size',
        'fourth_floor_rooms',
        'fourth_floor_baths',
        'fourth_floor_price',
        'fourth_floor_max_price',
        'fourth_floor_picture',
        'fourth_floor_description',
        'fifth_floor_title',
        'fifth_floor_size',
        'fifth_floor_max_size',
        'fifth_floor_rooms',
        'fifth_floor_baths',
        'fifth_floor_price',
        'fifth_floor_max_price',
        'fifth_floor_picture',
        'fifth_floor_description',
        'sixth_floor_title',
        'sixth_floor_size',
        'sixth_floor_max_size',
        'sixth_floor_rooms',
        'sixth_floor_baths',
        'sixth_floor_price',
        'sixth_floor_max_price',
        'sixth_floor_picture',
        'sixth_floor_description',
        'seventh_floor_title',
        'seventh_floor_size',
        'seventh_floor_max_size',
        'seventh_floor_rooms',
        'seventh_floor_baths',
        'seventh_floor_price',
        'seventh_floor_max_price',
        'seventh_floor_picture',
        'seventh_floor_description',
        'eighth_floor_title',
        'eighth_floor_size',
        'eighth_floor_max_size',
        'eighth_floor_rooms',
        'eighth_floor_baths',
        'eighth_floor_price',
        'eighth_floor_max_price',
        'eighth_floor_picture',
        'eighth_floor_description',
        'ninth_floor_title',
        'ninth_floor_size',
        'ninth_floor_max_size',
        'ninth_floor_rooms',
        'ninth_floor_baths',
        'ninth_floor_price',
        'ninth_floor_max_price',
        'ninth_floor_picture',
        'ninth_floor_description',
        'tenth_floor_title',
        'tenth_floor_size',
        'tenth_floor_max_size',
        'tenth_floor_rooms',
        'tenth_floor_baths',
        'tenth_floor_price',
        'tenth_floor_max_price',
        'tenth_floor_picture',
        'tenth_floor_description',
        'eleventh_floor_title',
        'eleventh_floor_size',
        'eleventh_floor_max_size',
        'eleventh_floor_rooms',
        'eleventh_floor_baths',
        'eleventh_floor_price',
        'eleventh_floor_max_price',
        'eleventh_floor_picture',
        'eleventh_floor_description',
        'twelfth_floor_title',
        'twelfth_floor_size',
        'twelfth_floor_max_size',
        'twelfth_floor_rooms',
        'twelfth_floor_baths',
        'twelfth_floor_price',
        'twelfth_floor_max_price',
        'twelfth_floor_picture',
        'twelfth_floor_description',
        'first_floor_sold',
        'second_floor_sold',
        'third_floor_sold',
        'fourth_floor_sold',
        'fifth_floor_sold',
        'sixth_floor_sold',
        'seventh_floor_sold',
        'eighth_floor_sold',
        'ninth_floor_sold',
        'tenth_floor_sold',
        'eleventh_floor_sold',
        'twelfth_floor_sold',
        'presentation',
        'purchase_vat',
        'title_deed_status',
        'title_deed_cost',
        'notary_fees',
        'valuation_cost',
        'drive_link',
        'plans_link',
        'word_link',
        'prices_link',
        'whatsapp_link',
        'location_info',
        'annual_tax',
        'min_downpayment',
        'ivr',
        ];

    public function propertyDetailTranslation()
    {
        $locale = Session::get('currentLocal');
        return $this->hasOne(PropertyDetailTranslation::class,'propertyDetail_id')
            ->where('locale',$locale);
    }

    public function propertyDetailTranslationEnglish()
    {
        return $this->hasOne(PropertyDetailTranslation::class,'propertyDetail_id')
            ->where('locale','EN');
    }

    public function floors() : HasMany
    {
        return $this->hasMany(PropertyFloor::class, 'property_details_id', 'id');
    }
}
