<?php
namespace App\Repositories;

use App\Models\PropertyDetail;

class PropertyDetailRepository implements IPropertyDetailRepository
{
    public function getById($id)
    {
        // TODO: Implement getById() method.
    }
    public function getByPropertyId($id)
    {
       return PropertyDetail::where('property_id',$id)->first();
    }
    public function add($data)
    {
      return PropertyDetail::create([
            'property_id'=> $data['propertyId'],
            'bed'=> $data['bed'],
            'bath'=> $data['bath'],
            'garage'=> $data['garage'],
            'blocks'=> $data['blocks'],
            'parcel'=> $data['parcel'],
            'floor'=> $data['floor'],
            'room_size'=> $data['room_size'],
            'content'=> $data['content'],
            'video'=> $data['video'],
            'landscape'=> $data['landscape'] ?? null,
            'view'=> $data['view'] ?? null,
            'available_floors'=> $data['available_floors'] ?? null,
            'balcony'=> $data['balcony'] ?? null,
            'heating'=> $data['heating'] ?? null,
            'emptiness'=> $data['emptiness'] ?? null,
            'citizenship'=> $data['citizenship'] ?? null,
            'cash'=> $data['cash'] ?? null,
            'installments'=> $data['installments'] ?? null,
            'maintenance_fee'=> $data['maintenance_fee'] ?? null,
            'creditability'=> $data['creditability'] ?? null,
            'building_age'=> $data['building_age'] ?? null,
            'units_infloors'=> $data['units_infloors'] ?? null,
            'convertability'=> $data['convertability'] ?? null,
            'total_units'=> $data['total_units'] ?? null,
            'title_deed_type'=> $data['title_deed_type'] ?? null,
            'delivery_month'=>$data['delivery_month'] ?? null,
            'deliver_year'=>$data['deliver_year'] ?? null,
            'payment_options'=>$data['payment_options'] ?? null,
            'inside_project'=>$data['inside_project'] ?? null,
            'island_no'=>$data['island_no'] ?? null,
            'sheet_no'=>$data['sheet_no'] ?? null,
            'presentation'=>$data['presentation'] ?? null,
            'precedent_value'=>$data['precedent_value'] ?? null,
            'gauge'=>$data['gauge'] ?? null,
            'first_floor_title'=>$data['first_floor_title'] ?? null,
            'first_floor_size'=>$data['first_floor_size'] ?? null,
            'first_floor_max_size'=>$data['first_floor_max_size'] ?? null,
            'first_floor_rooms'=>$data['first_floor_rooms'] ?? null,
            'first_floor_baths'=>$data['first_floor_baths'] ?? null,
            'first_floor_price'=>$data['first_floor_price'] ?? null,
            'first_floor_max_price'=>$data['first_floor_max_price'] ?? null,
            'first_floor_picture'=>$data['first_floor_picture'] ?? null,
            'second_floor_title'=>$data['second_floor_title'] ?? null,
            'second_floor_size'=>$data['second_floor_size'] ?? null,
            'second_floor_max_size'=>$data['second_floor_max_size'] ?? null,
            'second_floor_rooms'=>$data['second_floor_rooms'] ?? null,
            'second_floor_baths'=>$data['second_floor_baths'] ?? null,
            'second_floor_price'=>$data['second_floor_price'] ?? null,
            'second_floor_max_price'=>$data['second_floor_max_price'] ?? null,
            'second_floor_picture'=>$data['second_floor_picture'] ?? null,
            'third_floor_title'=>$data['third_floor_title'] ?? null,
            'third_floor_size'=>$data['third_floor_size'] ?? null,
            'third_floor_max_size'=>$data['third_floor_max_size'] ?? null,
            'third_floor_rooms'=>$data['third_floor_rooms'] ?? null,
            'third_floor_baths'=>$data['third_floor_baths'] ?? null,
            'third_floor_price'=>$data['third_floor_price'] ?? null,
            'third_floor_max_price'=>$data['third_floor_max_price'] ?? null,
            'third_floor_picture'=>$data['third_floor_picture'] ?? null,
            'fourth_floor_title'=>$data['fourth_floor_title'] ?? null,
            'fourth_floor_size'=>$data['fourth_floor_size'] ?? null,
            'fourth_floor_max_size'=>$data['fourth_floor_max_size'] ?? null,
            'fourth_floor_rooms'=>$data['fourth_floor_rooms'] ?? null,
            'fourth_floor_baths'=>$data['fourth_floor_baths'] ?? null,
            'fourth_floor_price'=>$data['fourth_floor_price'] ?? null,
            'fourth_floor_max_price'=>$data['fourth_floor_max_price'] ?? null,
            'fourth_floor_picture'=>$data['fourth_floor_picture'] ?? null,
            'fifth_floor_title'=>$data['fifth_floor_title'] ?? null,
            'fifth_floor_size'=>$data['fifth_floor_size'] ?? null,
            'fifth_floor_max_size'=>$data['fifth_floor_max_size'] ?? null,
            'fifth_floor_rooms'=>$data['fifth_floor_rooms'] ?? null,
            'fifth_floor_baths'=>$data['fifth_floor_baths'] ?? null,
            'fifth_floor_price'=>$data['fifth_floor_price'] ?? null,
            'fifth_floor_max_price'=>$data['fifth_floor_max_price'] ?? null,
            'fifth_floor_picture'=>$data['fifth_floor_picture'] ?? null,
            'sixth_floor_title'=>$data['sixth_floor_title'] ?? null,
            'sixth_floor_size'=>$data['sixth_floor_size'] ?? null,
            'sixth_floor_max_size'=>$data['sixth_floor_max_size'] ?? null,
            'sixth_floor_rooms'=>$data['sixth_floor_rooms'] ?? null,
            'sixth_floor_baths'=>$data['sixth_floor_baths'] ?? null,
            'sixth_floor_price'=>$data['sixth_floor_price'] ?? null,
            'sixth_floor_max_price'=>$data['sixth_floor_max_price'] ?? null,
            'sixth_floor_picture'=>$data['sixth_floor_picture'] ?? null,
            'seventh_floor_title'=>$data['seventh_floor_title'] ?? null,
            'seventh_floor_size'=>$data['seventh_floor_size'] ?? null,
            'seventh_floor_max_size'=>$data['seventh_floor_max_size'] ?? null,
            'seventh_floor_rooms'=>$data['seventh_floor_rooms'] ?? null,
            'seventh_floor_baths'=>$data['seventh_floor_baths'] ?? null,
            'seventh_floor_price'=>$data['seventh_floor_price'] ?? null,
            'seventh_floor_max_price'=>$data['seventh_floor_max_price'] ?? null,
            'seventh_floor_picture'=>$data['seventh_floor_picture'] ?? null,
            'eighth_floor_title'=>$data['eighth_floor_title'] ?? null,
            'eighth_floor_size'=>$data['eighth_floor_size'] ?? null,
            'eighth_floor_max_size'=>$data['eighth_floor_max_size'] ?? null,
            'eighth_floor_rooms'=>$data['eighth_floor_rooms'] ?? null,
            'eighth_floor_baths'=>$data['eighth_floor_baths'] ?? null,
            'eighth_floor_price'=>$data['eighth_floor_price'] ?? null,
            'eighth_floor_max_price'=>$data['eighth_floor_max_price'] ?? null,
            'eighth_floor_picture'=>$data['eighth_floor_picture'] ?? null,
            'ninth_floor_title'=>$data['ninth_floor_title'] ?? null,
            'ninth_floor_size'=>$data['ninth_floor_size'] ?? null,
            'ninth_floor_max_size'=>$data['ninth_floor_max_size'] ?? null,
            'ninth_floor_rooms'=>$data['ninth_floor_rooms'] ?? null,
            'ninth_floor_baths'=>$data['ninth_floor_baths'] ?? null,
            'ninth_floor_price'=>$data['ninth_floor_price'] ?? null,
            'ninth_floor_max_price'=>$data['ninth_floor_max_price'] ?? null,
            'ninth_floor_picture'=>$data['ninth_floor_picture'] ?? null,
            'tenth_floor_title'=>$data['tenth_floor_title'] ?? null,
            'tenth_floor_size'=>$data['tenth_floor_size'] ?? null,
            'tenth_floor_max_size'=>$data['tenth_floor_max_size'] ?? null,
            'tenth_floor_rooms'=>$data['tenth_floor_rooms'] ?? null,
            'tenth_floor_baths'=>$data['tenth_floor_baths'] ?? null,
            'tenth_floor_price'=>$data['tenth_floor_price'] ?? null,
            'tenth_floor_max_price'=>$data['tenth_floor_max_price'] ?? null,
            'tenth_floor_picture'=>$data['tenth_floor_picture'] ?? null,
            'eleventh_floor_title'=>$data['eleventh_floor_title'] ?? null,
            'eleventh_floor_size'=>$data['eleventh_floor_size'] ?? null,
            'eleventh_floor_max_size'=>$data['eleventh_floor_max_size'] ?? null,
            'eleventh_floor_rooms'=>$data['eleventh_floor_rooms'] ?? null,
            'eleventh_floor_baths'=>$data['eleventh_floor_baths'] ?? null,
            'eleventh_floor_price'=>$data['eleventh_floor_price'] ?? null,
            'eleventh_floor_max_price'=>$data['eleventh_floor_max_price'] ?? null,
            'eleventh_floor_picture'=>$data['eleventh_floor_picture'] ?? null,
            'twelfth_floor_title'=>$data['twelfth_floor_title'] ?? null,
            'twelfth_floor_size'=>$data['twelfth_floor_size'] ?? null,
            'twelfth_floor_max_size'=>$data['twelfth_floor_max_size'] ?? null,
            'twelfth_floor_rooms'=>$data['twelfth_floor_rooms'] ?? null,
            'twelfth_floor_baths'=>$data['twelfth_floor_baths'] ?? null,
            'twelfth_floor_price'=>$data['twelfth_floor_price'] ?? null,
            'twelfth_floor_max_price'=>$data['twelfth_floor_max_price'] ?? null,
            'twelfth_floor_picture'=>$data['twelfth_floor_picture'] ?? null,
            'first_floor_sold'=>$data['first_floor_sold'],
            'second_floor_sold'=>$data['second_floor_sold'],
            'third_floor_sold'=>$data['third_floor_sold'],
            'fourth_floor_sold'=>$data['fourth_floor_sold'],
            'fifth_floor_sold'=>$data['fifth_floor_sold'],
            'sixth_floor_sold'=>$data['sixth_floor_sold'],
            'seventh_floor_sold'=>$data['seventh_floor_sold'],
            'eighth_floor_sold'=>$data['eighth_floor_sold'],
            'ninth_floor_sold'=>$data['ninth_floor_sold'],
            'tenth_floor_sold'=>$data['tenth_floor_sold'],
            'eleventh_floor_sold'=>$data['eleventh_floor_sold'],
            'twelfth_floor_sold'=>$data['twelfth_floor_sold'],
            'ivr'=> $data['ivr'],
            'drive_link'=> $data['drive_link'],
            'plans_link'=> $data['plans_link'],
            'word_link'=> $data['word_link'],
            'prices_link'=> $data['prices_link'],
            'whatsapp_link'=> $data['whatsapp_link'],
        ]);
    }

    public function update($data, $id)
    {
        $propertyDetail = $this->getByPropertyId($id);
        $propertyDetail->update($data);
    }

    public function delete($id)
    {
        // TODO: Implement delete() method.
    }
}
